repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: update-readme
        name: Update README with tree output
        entry: ./.update.sh
        language: script
        stages: [pre-commit]
