tap "chainguard-dev/tap", trusted: true
tap "defenseunicorns/tap", trusted: true
tap "hashicorp/tap", trusted: true
tap "homebrew/core"
tap "willswire/tap", trusted: true
# CLI tool for working with Architecture Decision Records
brew "adr-tools"
# Build OCI images from APK packages directly without Dockerfile
brew "apko"
# General-purpose data compression with high compression ratio
brew "xz"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Official Amazon AWS command-line interface
brew "awscli"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# AST-based pattern checker for JavaScript
brew "eslint"
# GitHub command-line tool
brew "gh"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Git extension for versioning large files
brew "git-lfs"
# Compute various size metrics for a Git repository
brew "git-sizer"
# Audit git repos for secrets
brew "gitleaks"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Fast linters runner for Go
brew "golangci-lint"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Kubernetes package manager
brew "helm"
# Language server for Helm
brew "helm-ls"
# Handy way to save and run project-specific commands
brew "just"
# Little helper to run CNCF's k3s in Docker
brew "k3d"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Build APKs from source code
brew "melange"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Manage multiple Node.js versions
brew "nvm"
# Tools and libraries for smart cards
brew "opensc"
# Drop-in replacement for Terraform. Infrastructure as Code Tool
brew "opentofu"
# OCI Registry As Storage
brew "oras"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Tools to manage objects on PKCS#11 crypotographic tokens
brew "pkcs11-tools"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Rsync for cloud storage
brew "rclone"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# S/MIME signing utility for use with Git
brew "smimesign"
# Editor of encrypted files
brew "sops"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Linter for Terraform files
brew "tflint"
# Simplified and community-driven man pages
brew "tldr"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Little beautifier tool for xcodebuild
brew "xcbeautify"
# Build server protocol implementation for integrating Xcode with sourcekit-lsp
brew "xcode-build-server"
# Linter for YAML files
brew "yamllint"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# CLI for Unicorn Delivery Service
brew "defenseunicorns/tap/uds"
# The Airgap Native Packager Manager for Kubernetes
brew "defenseunicorns/tap/zarf"
# Packer
brew "hashicorp/tap/packer"
# rolesanywhere-credential-helper implements the signing process for IAM Roles Anywhere
brew "willswire/tap/aws_signing_helper"
# Ultra-fast static analysis tool for searching code patterns across 30+ languages
brew "willswire/tap/opengrep"
# Like tee but with emojis 🍵
brew "willswire/tap/teemoji"
# Command-line interface for 1Password
cask "1password-cli"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
cargo "tree-sitter-cli"
